dateModified: 1719156925
email:
  fromEmail: matt@mattisawesome.com
  fromName: localtest
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    6f47078b-e048-4afe-a741-618451fa643a: Page # Page
    7df39160-9b09-4516-b337-1a83036a4824: Test # Test
    cede2bfb-5113-4333-b17d-135d483c2762: localtest # localtest
    df6ef6dc-716a-41cf-982f-bfe668fb9ad6: localtest # localtest
system:
  edition: solo
  live: true
  name: localtest
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
